let from_wasm_step : Compiler_wasm.compiler_step -> Compiler.compiler_step = function
| Typing -> Typing
| ParamsExpansion -> ParamsExpansion
| RemoveAssertion -> RemoveAssertion
| InsertRenaming -> InsertRenaming
| WintWord -> WintWord
| ArrayCopy -> ArrayCopy
| AddArrInit -> AddArrInit
| LowerSpill -> LowerSpill
| Inlining -> Inlining
| RemoveUnusedFunction -> RemoveUnusedFunction
| Unrolling -> Unrolling
| Splitting -> Splitting
| Renaming -> Renaming
| RemovePhiNodes -> RemovePhiNodes
| DeadCode_Renaming -> DeadCode_Renaming
| RemoveArrInit -> RemoveArrInit
| MakeRefArguments -> MakeRefArguments
| RegArrayExpansion -> RegArrayExpansion
| RemoveGlobal -> RemoveGlobal
| LoadConstantsInCond -> LoadConstantsInCond
| LowerInstruction -> LowerInstruction
| PropagateInline -> PropagateInline
| SLHLowering -> SLHLowering
| LowerAddressing -> LowerAddressing
| StackAllocation -> StackAllocation
| RemoveReturn -> RemoveReturn
| RegAllocation -> RegAllocation
| DeadCode_RegAllocation -> DeadCode_RegAllocation
| Linearization -> Linearization
| StackZeroization -> StackZeroization
| Tunneling -> Tunneling
| Assembly -> Assembly

let to_wasm_step : Compiler.compiler_step -> Compiler_wasm.compiler_step = function
| Typing -> Typing
| ParamsExpansion -> ParamsExpansion
| RemoveAssertion -> RemoveAssertion
| InsertRenaming -> InsertRenaming
| WintWord -> WintWord
| ArrayCopy -> ArrayCopy
| AddArrInit -> AddArrInit
| LowerSpill -> LowerSpill
| Inlining -> Inlining
| RemoveUnusedFunction -> RemoveUnusedFunction
| Unrolling -> Unrolling
| Splitting -> Splitting
| Renaming -> Renaming
| RemovePhiNodes -> RemovePhiNodes
| DeadCode_Renaming -> DeadCode_Renaming
| RemoveArrInit -> RemoveArrInit
| MakeRefArguments -> MakeRefArguments
| RegArrayExpansion -> RegArrayExpansion
| RemoveGlobal -> RemoveGlobal
| LoadConstantsInCond -> LoadConstantsInCond
| LowerInstruction -> LowerInstruction
| PropagateInline -> PropagateInline
| SLHLowering -> SLHLowering
| LowerAddressing -> LowerAddressing
| StackAllocation -> StackAllocation
| RemoveReturn -> RemoveReturn
| RegAllocation -> RegAllocation
| DeadCode_RegAllocation -> DeadCode_RegAllocation
| Linearization -> Linearization
| StackZeroization -> StackZeroization
| Tunneling -> Tunneling
| Assembly -> Assembly
