NAME="SHA256-OPT"
name="sha256-opt"

MSG_01="foo bar gee"

run_algorithm_tests() {
  local NB_REPEAT=$1

  local MSG_02=$(generate_string 256)
  local MSG_03=$(generate_string 2048)

  run_benchmark   "11" "true" $NB_REPEAT 20000000 "$MSG_01"
  run_benchmark  "512" "true" $NB_REPEAT  2420000 "$MSG_02"
  run_benchmark "4096" "true" $NB_REPEAT   344000 "$MSG_03"
}
